### ISSUE TITLE
Support -2 for "do not merge"

### ISSUE THREAD

**Issue by nikreiman** [jhaals/tutter#6]
It would be nice if tutter had some concept of -2 (aka Gerrit's "Do not merge") for changes which are dangerous and thus should not be automatically merged. Perhaps :hankey: ? :)

**Comment by jhaals** [comment]
@nikreiman totally agree. However that logic should go into the specific tutter action(plugin). The existing action that mimic the review workflow in gerrit is [tutter-sppuppet](https://github.com/jhaals/tutter-sppuppet). Open an issue in that project instead.

**Comment by nikreiman** [comment]
True, good point. I'm still a bit new to tutter. :) Resubmitted here: https://github.com/jhaals/tutter-sppuppet/issues/12
